-- 1. LENGTH()
SELECT title,LENGTH(title) FROM ARTICLE_VERSION;

-- 2. UPPER()
SELECT UPPER(username) FROM USER;

-- 3. LOWER()
SELECT LOWER(username) FROM USER;

-- 4. CONCAT()
SELECT CONCAT(username, ' ', email) FROM USER;

-- 5. REPLACE()
SELECT REPLACE(email,'gmail.com','yahoo.com') FROM USER;

-- 6. REVERSE()
SELECT REVERSE(email) FROM USER;

-- 7. ROUND()
SELECT ROUND(123.4567,2);

-- 8. CEIL()
SELECT CEILING(12.1);

-- 9. FLOOR()
SELECT FLOOR(13.8);

-- 10. ABS()
SELECT ABS(-100);

-- 11. MOD()
SELECT MOD(10,3);

-- 12. POWER()
SELECT POWER(10,2);

-- 13. SQRT()
SELECT SQRT(9);

-- 14. TRUNCATE()
SELECT TRUNCATE(16.89791,2);

-- 15. IFNULL()
SELECT IFNULL(NULL,10000); -- REPLACE NULL WITH VALUE 