using MySql.Data.MySqlClient;
namespace CSharpDemo.DatabaseWithCSharp;

internal static class CreateTag {

    public static void Run() {

        string name = TagInput.ReadName("Tag name: ");
        
        // insert if not exists
        // if exists update with tag_id with itself
        const string sql = """
        INSERT INTO TAG (name)
        VALUES (@name)
        ON DUPLICATE KEY UPDATE tag_id = LAST_INSERT_ID(tag_id);
        """;

        using MySqlConnection connection = DatabaseConnection.Create();
        connection.Open();

        using var command = new MySqlCommand(sql, connection);
        command.Parameters.Add("@name",MySqlDbType.VarChar,100).Value = name;

        int rowsAffected = command.ExecuteNonQuery();
        Console.WriteLine($"Rows affected: {rowsAffected}");

        // LastInsertedId gives the ID generated by the last INSERT, when applicable.
        Console.WriteLine($"Tag created or already existed. ID: {command.LastInsertedId}");
    }
}